YSManagmentSystem.web/Controllers/BrandController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using YSManagmentSystem.BLL.Categories;
using YSManagmentSystem.BLL.Products;
using YSManagmentSystem.Domain.Product;
using YSManagmentSystem.web.Models.DataTable;

namespace YSManagmentSystem.web.Controllers
{
    public class BrandController : Controller
    {
        private readonly IBrandServices _brand;
        private readonly IProductServices _product;
        public BrandController(IBrandServices brand,IProductServices product)
        {
            _brand = brand;
            _product = product;
        }

        public IActionResult Index()
        {
            var bnd = _product.GetAllBrand();

            return View(bnd);
        }

        [HttpGet]
        public IActionResult AddOrEditBrand(int? id)
        {
            if (id > 0)
            {
                var bnd = _brand.GetBrandByID(id.GetValueOrDefault());
                return View(bnd);
            }
            else
            {
                ViewBag.BId = new SelectList(_product.GetAllBrand().ToList(), "Id", "BrandName");

                return View();

            }

        }

        [HttpPost]

        public IActionResult AddOrEditBrand(int? id, Brand bnd)
        {
            long result = 0;
            int Status;
            string Value;

            if (id > 0)
            {
                result = _brand.UpdateBrand(bnd);
                if (result > 0)
                {
                    Status = 200;
                    Value = Url.Content("~/Design/View/");
                }
                else
                {
                    Status = 500;
                    Value = "There is some error at server side";
                }
            }
            else
            {
                ViewBag.BId = new SelectList(_product.GetAllBrand().ToList(), "Id", "BrandName");

                result = _brand.AddBrand(bnd);
                if (result > 0)
                {
                    Status = 200;
                    Value = Url.Content("~/Design/View/");
                }
                else
                {
                    Status = 500;
                    Value = "There is some error at server side";
                }
            }
            return Json(new { status = Status, value = Value });
        }


        [HttpGet]
        public IActionResult DetailBrand(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var sup = _brand.GetBrandByID(id.GetValueOrDefault());
            if (sup == null)

                return NotFound();

            return View(sup);
        }

        //[HttpGet]
        //public IActionResult EditProduct(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }
        //    var prod = _product.GetProductByID(id.GetValueOrDefault());
        //    if (prod == null)

        //        return NotFound();

        //    return View(prod);
        //}

        //[HttpPost]
        //public IActionResult EditProduct(int id,Product product) 
        //{
        //    long result = 0;
        //    int Status;
        //    string Value;

        //    if (ModelState.IsValid)
        //    {
        //        result = _product.UpdateProduct(product);
        //        if (result > 0)
        //        {
        //            Status = 200;
        //            Value = Url.Content("~/Design/View/");
        //        }
        //        else
        //        {
        //            Status = 500;
        //            Value = "There is some error at server side";
        //        }
        //    }
        //    else
        //    {
        //        Status = 500;
        //        Value = "There is some error at client side";
        //    }
        //    return Json(new { status = Status, value = Value });
        //}

        //Delete user

        [HttpGet]
        public IActionResult DeleteBrand(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }
            _brand.DeleteBrand(id.GetValueOrDefault());
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult DeleteBrand(int id, Brand bnd)
        {
            if (_brand.DeleteBrand(id) > 0)
            {
                return RedirectToAction("Index");
            }
            return View(bnd);
        }

        //Data Table, Searching, sorting, Paging, Total Count,Filtering
        [HttpPost]
        public JsonResult GetAllBrand()
        {
            var request = new DTReq();
            request.draw = Convert.ToInt32(Request.Form["draw"]);
            request.StartRowIndex = Convert.ToInt32(Request.Form["start"]);
            request.SortExpression = Request.Form["order[0][dir]"];
            request.PageSize = Convert.ToInt32(Request.Form["length"]);
            request.SearchText = Request.Form["search[value]"];



            var pro = _brand.GetAllBrandDT(request).Result;
            return Json(pro);
        }
    }
}

YSManagmentSystem.web/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using YSManagmentSystem.BLL.User;
using YSManagmentSystem.Domain.Product;
using YSManagmentSystem.Domain.User;
using YSManagmentSystem.web.Models.DataTable;

namespace YSManagmentSystem.web.Controllers
{
    public class UserController : Controller
    {
        
        private readonly IUserServices _user;
        //private readonly IRoleServices _role;
        private readonly IWebHostEnvironment _webHostEnvironment;


        private class ICustomICustomClaimsCookieSignInHelper { }
        public UserController(IUserServices user, IWebHostEnvironment webHostEnvironment /*IRoleServices role*/)
        {
            _user = user;
            _webHostEnvironment = webHostEnvironment;
            //_role = role;
        }

        //[Authorize(Roles = "Admin,User,Editor")]
        public IActionResult Index(UserDetail uD)
        {
            var user = _user.GetAllUsers(uD);
            return View(user);
        }
        [HttpGet]
        public IActionResult GetUserByID(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }
            var user = _user.GetUserByID(id.GetValueOrDefault());
            if (user == null)

                return NotFound();

            return View(user);
        }
        public IActionResult Profile()
        {
            var email = HttpContext.Response.HttpContext.User.Identity.Name;
            var user = _user.GetUserByEmail(email);

            return View();
        }

        // Change Password after login 
        //[HttpGet]
        //[Authorize]
        //public IActionResult ChangePassword()
        //{
        //    return View();
        //}
        //[HttpPost]

        //public IActionResult ChangePassword(ChangePassword dto)
        //{

        //    if (ModelState.IsValid)
        //    {
        //        var email = HttpContext.Response.HttpContext.User.Identity.Name;
        //        var user = _user.GetUserByEmail(email);
        //        if (!_user.VerifyPasswordHash(user.Password, dto.OldPassword))
        //        {
        //            return BadRequest("Your password does not macth.");
        //        }
        //        if (dto.NewPassword == dto.ConfirmPassword)
        //        {
        //            var hash = _user.CreatePasswordHash(dto.NewPassword);
        //            _user.UpdatePassword(email, hash);
        //        }
        //        else
        //        {
        //            return BadRequest("Password does not match.");
        //        }
        //        return RedirectToAction("Login");
        //    }
        //    else
        //    {
        //        return BadRequest("OOP! Wrong Credentials");
        //    }
        //}


        ////Image Upload

        //[HttpGet]
        //public IActionResult ImageUpload()
        //{
        //    return View();
        //}

        //[HttpPost]
        //public IActionResult ImageUpload(ImageModel dto)
        //{
        //    string email = HttpContext.Response.HttpContext.User.FindClaim("id").ToString();
        //    string[] ne = email.Split(':');
        //    int e = Convert.ToInt32(ne[1]);
        //    string userimg = _user.GetUserByID(e).Image;
        //    DateTime date = DateTime.UtcNow;

        //    if (dto.ImageFile != null)
        //    {
        //        string path = Path.Combine(_webHostEnvironment.WebRootPath, "User/Img");

        //        if (!string.Equals(userimg, "~/User/Img/User.png"))
        //        {
        //            string oldImagePath = Path.Combine(path, userimg);
        //            if (System.IO.File.Exists(oldImagePath))
        //            {
        //                System.IO.File.Delete(oldImagePath);
        //            }
        //        }
        //        long tick = date.Ticks;
        //        //string guid = Guid.NewGuid().ToString();
        //        string imageName = tick + "_" + dto.ImageFile.FileName;
        //        string filePath = Path.Combine(path, imageName);
        //        //FileStream fs = new FileStream(filePath, FileMode.Create);
        //        //dto.ImageFile.CopyToAsync(fs);
        //        using (var fileStream = new FileStream(filePath, FileMode.Create))
        //        {
        //            dto.ImageFile.CopyTo(fileStream);
        //            fileStream.Close();
        //        }

        //        dto.ImageName = imageName;
        //    }


        //    _user.UpadateUserImage(dto.ImageName, e);
        //    return View();

        //}


        ////public IActionResult ImageUpload(List<IFormFile> postedFiles)
        ////{

        ////    string path = Path.Combine(_webHostEnvironment.WebRootPath, "Images");
        ////    if (!Directory.Exists(path))
        ////    {
        ////        Directory.CreateDirectory(path);
        ////    }

        ////    List<string> uploadedFiles = new List<string>();
        ////    foreach (IFormFile postedFile in postedFiles)
        ////    {
        ////        string fileName = Path.GetFileName(postedFile.FileName);
        ////        string imagePath = Path.Combine(path, fileName);
        ////        using (FileStream stream = new FileStream(imagePath, FileMode.Create))
        ////        {
        ////            postedFile.CopyTo(stream);
        ////            uploadedFiles.Add(fileName);
        ////            ViewBag.Message += string.Format("<b>{0}</b> Images.<br />", fileName);
        ////        }
        ////        var email = HttpContext.Response.HttpContext.User.Identity.Name;
        ////        var userId = _user.GetUserByEmail(email).id;
        ////        var pathToDB = @"~\wwwroot\Images\" + fileName;
        ////        var user = new Users
        ////        {
        ////            id = userId,
        ////            Image = pathToDB

        ////        };
        ////        _user.UpadateUserImage(user);


        ////        TempData["Success"] = "The product has been added!";
        ////    }
        ////        return RedirectToAction("Index", "Employee");

        ////}
        ////[HttpGet]
        ////public IActionResult ImageUpload()
        ////{
        ////    return View();
        ////}
        ////[HttpPost]
        ////[ValidateAntiForgeryToken]
        ////public IActionResult ImageUpload([Bind("ImageId,Title,ImageName")] ImageModel imageModel)
        ////{
        ////    if (ModelState.IsValid)
        ////    {
        ////        //Save image to wwwroot/image
        ////        string wwwRootPath = _webHostEnvironment.WebRootPath;
        ////        string fileName = Path.GetFileNameWithoutExtension(imageModel.ImageFile.FileName);
        ////        string extension = Path.GetExtension(imageModel.ImageFile.FileName);
        ////        imageModel.ImageName = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
        ////        string path = Path.Combine(wwwRootPath, fileName);
        ////        using (var fileStream = new FileStream(path, FileMode.Create))
        ////        {
        ////            imageModel.ImageFile.CopyTo(fileStream);
        ////        }
        ////        var email = HttpContext.Response.HttpContext.User.Identity.Name;
        ////        var userId = _user.GetUserByEmail(email).id;
        ////        var pathToDB = @"~\wwwroot\Images\" + fileName;

        ////        _user.UpadateUserImage(pathToDB,userId);
        ////        //var deleteImg = (User.Identity as ClaimsIdentity).Claims.Where(c => c.Type == "Image").FirstOrDefault();
        ////        //if (deleteImg != null)
        ////        //{
        ////        //    string oldimg = Request.Path(deleteImg.Value.ToString());
        ////        //    if (System.IO.File.Exists(oldimg))
        ////        //    {
        ////        //        System.IO.File.Delete(oldimg);
        ////        //    }
        ////        //}
        ////        ViewBag.Message = "profile picture updated successfully.";

        ////    }
        ////    return RedirectToAction("Index", "Employee");
        ////}

        ////public IActionResult DeleteImage(int? id)
        ////{
        ////    return View();
        ////}

        ////[HttpPost]
        ////[ValidateAntiForgeryToken]
        ////public IActionResult DeleteConfirmed(int id)
        ////{
        ////    var imageModel =  _user.GetUserByID(id).Image;

        ////    //delete image from wwwroot/image
        ////    var imagePath = Path.Combine(_webHostEnvironment.WebRootPath, "Image", imageModel.);
        ////    if (System.IO.File.Exists(imagePath))
        ////        System.IO.File.Delete(imagePath);

        ////    _user.DeleteUserImage(imageModel);
        ////    return RedirectToAction("Index","Employee");
        ////}
        //public async Task<IActionResult> Logout()
        //{
        //    await HttpContext.SignOutAsync();
        //    return LocalRedirect("~/");
        //}

        public IActionResult ProfileView()
        {

            return View();
        }

        // User Image Delete

        [HttpGet]
        public IActionResult DeleteUserImage(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var user = _user.GetUserByID(id.GetValueOrDefault());
            if (user == null)

                return NotFound();

            return View(user);
        }

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public IActionResult DeleteUserImage(ImageModel dto)
        //{
        //    var email = HttpContext.Response.HttpContext.User.Identity.Name;
        //    var userimg = _user.GetUserByEmail(email).Image;

        //    if (dto.ImageFile != null)
        //    {
        //        string uploadsDir = Path.Combine(_webHostEnvironment.WebRootPath, "User/Img");

        //        if (!string.Equals(userimg, "User.png"))
        //        {

YSManagmentSystem.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - YSManagmentSystem.web</title>
    
    <link href="/datatables/css/datatables.bootstrap5.min.css" rel="stylesheet" />
    <link href="/datatables/css/datatables.bootstrap5.css" rel="stylesheet" />

    <link href="/datatables/css/jquery.datatables.css" rel="stylesheet" />
    <link href="/datatables/css/jquery.datatables.min.css" rel="stylesheet" />

    <link href="/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />

    <link href="/css/sidebar.css" rel="stylesheet" />
    <link href="/css/validation.css" rel="stylesheet" />
    <link href="/css/site.css" rel="stylesheet" />
    
    <link href="/font-awesome/css/all.css" rel="stylesheet" />
    <link href="/font-awesome/css/all.min.css" rel="stylesheet" />

    <link href="~/limonte-sweetalert2/sweetalert2.css" rel="stylesheet" />
    <link href="~/limonte-sweetalert2/sweetalert2.min.css" rel="stylesheet" />
</head>
<body>

    <div class="wrapper d-flex align-items-stretch">
        <partial name="_SideBarPartialView "></partial>
        <div id="content" class="p-4 p-md-5">
            <partial name="_NavBarPartialView"></partial>
   @RenderBody()
        </div>
   </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - YS Management System - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <!-- Scripts -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="@Url.Content("~/lib/jquery-validation/dist/jquery.validate.js")"></script>
    <script src="@Url.Content("~/lib/jquery-validation/dist/additional-methods.js")"></script>
    <script src="/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="/datatables/js/jquery.datatables.min.js"></script>
    <script src="/datatables/js/datatables.datatables.min.js"></script>
    <script src="/datatables/js/datatables.bootstrap.min.js"></script>
    <script src="/datatables/js/datatables.jqueryui.min.js"></script>
    <script src="/datatables/js/datatables.bootstrap5.min.js"></script>
    <script src="/js/bootstrapnotify.js"></script>
    <script src="~/limonte-sweetalert2/sweetalert2.all.js"></script>
    <script src="~/limonte-sweetalert2/sweetalert2.all.min.js"></script>
    
    


    @RenderSection("Scripts", required: false)
</body>
</html>

YSManagmentSystem.web/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - YSManagment.WEB</title>

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="icon" type="image/png" sizes="16x16" href="~/" />
    <!-- Pignose Calender -->
    <link href="~/Temp/plugins/pg-calendar/css/pignose.calendar.min.css" rel="stylesheet" />
    <!-- Chartist -->
    @*<link rel="stylesheet" href="~/Temp/plugins/chartist/css/chartist.min.css" />
    <link rel="stylesheet" href="~/Temp/plugins/chartist-plugin-tooltips/css/chartist-plugin-tooltip.css" />*@
    
   
   
    <link href="/css/validation.css" rel="stylesheet" />
    <link href="/css/site.css" rel="stylesheet" />
    
    <link href="/font-awesome/css/all.css" rel="stylesheet" />
    <link href="/font-awesome/css/all.min.css" rel="stylesheet" />

    <link href="~/limonte-sweetalert2/sweetalert2.css" rel="stylesheet" />
    <link href="~/limonte-sweetalert2/sweetalert2.min.css" rel="stylesheet" />
    <!-- Custom Stylesheet -->
    <link href="~/Temp/css/style.css" rel="stylesheet" />
    
</head>
<body>
   

    <!--*******************
        Preloader start
    ********************-->
    <div id="preloader">
        <div class="loader">
            <svg class="circular" viewBox="25 25 50 50">
                <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="3" stroke-miterlimit="10" />
            </svg>
        </div>
    </div>
    <!--*******************
        Preloader end
    ********************-->


    <div class="nav-header">
        <div class="brand-logo">
            <a asp-area="" asp-controller="Home" asp-action="Index">
                <b class="logo-abbr"><img src="~/" alt="" /> </b>
                <span class="logo-compact"><img src="~/" alt="" /></span>
                <span class="brand-title">
                    <img src="~/" alt="">
                </span>
            </a>
        </div>
    </div>




    <partial name="_TopBar" />

    <partial name="_sideBar" />

    <div class="content-body">


        <div class="container-fluid">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>
    <br />
    <br />
  
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - YS Management System - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <!--**********************************
        Scripts
    ***********************************-->
    <script src="~//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="~/Temp/plugins/common/common.min.js"></script>
    <script src="~/Temp/js/custom.min.js"></script>
    <script src="~/Temp/js/settings.js"></script>
    <script src="~/Temp/js/gleek.js"></script>
    <script src="~/Temp/js/styleSwitcher.js"></script>

    <!-- Chartjs -->
    <script src="~/Temp/plugins/chart.js/Chart.bundle.min.js"></script>
    <!-- Circle progress -->
    <script src="~/Temp/plugins/circle-progress/circle-progress.min.js"></script>
    <!-- Datamap -->
    <script src="~/Temp/plugins/d3v3/index.js"></script>
    <script src="~/Temp/plugins/topojson/topojson.min.js"></script>
    <script src="~/Temp/plugins/datamaps/datamaps.world.min.js"></script>
    <!-- Morrisjs -->
    <script src="~/Temp/plugins/raphael/raphael.min.js"></script>
    <script src="~/Temp/plugins/morris/morris.min.js"></script>
    <!-- Pignose Calender -->
    <script src="~/Temp/plugins/moment/moment.min.js"></script>
    <script src="~/Temp/plugins/pg-calendar/js/pignose.calendar.min.js"></script>
    <!-- ChartistJS -->
    <script src="~/Temp/plugins/chartist/js/chartist.min.js"></script>
    <script src="~/Temp/plugins/chartist-plugin-tooltips/js/chartist-plugin-tooltip.min.js"></script>


    <script src="@Url.Content("~/lib/jquery-validation/dist/jquery.validate.js")"></script>
    <script src="@Url.Content("~/lib/jquery-validation/dist/additional-methods.js")"></script>
    <script src="/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="/datatables/js/jquery.datatables.min.js"></script>
    <script src="/datatables/js/datatables.datatables.min.js"></script>
    <script src="/datatables/js/datatables.bootstrap.min.js"></script>
    <script src="/datatables/js/datatables.jqueryui.min.js"></script>
    <script src="/datatables/js/datatables.bootstrap5.min.js"></script>
    <script src="/js/bootstrapnotify.js"></script>
    <script src="~/limonte-sweetalert2/sweetalert2.all.js"></script>
    <script src="~/limonte-sweetalert2/sweetalert2.all.min.js"></script>


    <script src="~/Temp/js/dashboard/dashboard-1.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

YSManagmentSystem.web/Views/Shared/_NavBarPartialView.cshtml
@using Microsoft.AspNetCore.Http;
@using YSManagmentSystem.Domain.User;

 <!-- Page Content  -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">

        <button type="button" id="sidebarCollapse" class="btn btn-primary">
            <i class="fa fa-bars"></i>
            <span class="sr-only">Toggle Menu</span>
        </button>
        <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fa fa-bars"></i>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="nav navbar-nav ml-auto" style="margin-left:400px">
                <li class="nav-item active">
                    <a class="nav-link" href="/Account/Login">Home</a>
                </li>
                @* <li class="nav-item active">
                <a class="nav-link" href="#">About</a>
                </li>*@
                <li class="nav-item">
                    <div class="nav-link">
                        <button class="btn btn-primary " type="button" style="width: auto; text-align: center; " data-toggle="dropdown" aria-expanded="true">
                            Welcome @Url.Content(CustomClaims.Name(User)) <img src="~/User/Img/@Url.Content(CustomClaims.Image(User))" alt ="" class="image_Profile" />
                            <i class="fa fa-caret-down"></i>
                        </button>
                        <ul class="dropdown-menu" style="padding:inherit;margin-left:920px">
                            <li style="display: block;"><a href="~/User/ProfileView">View Profile</a></li>
                            <li style="display: block;"><a href="~/User/ChangePassword">Change Password</a></li>
                            <li style="display: block;"><a href="~/Account/Logout">Sign Out</a></li>
                        </ul>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

YSManagmentSystem.web/Views/Shared/_SideBarPartialView .cshtml
<nav id="sidebar">
    <div class="p-4 pt-5">
        <a href="/User/ImageUpload" class="img logo rounded-circle mb-5"></a>
        <ul class="list-unstyled components mb-5">
            <li class="active">
                <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Home</a>
                <ul class="collapse list-unstyled" id="homeSubmenu">
                    <li>
                        <a href="/User/Index">Home</a>
                    </li>
                    <li>
                        <a href="/Images/Index">Image Crop</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Users</a>
                <ul class="collapse list-unstyled" id="pageSubmenu">
                    <li>
                        <a href="/User/Index">Users Detail</a>
                    </li>
                    <li>
                        <a href="/User/UpdateUser">Edit User</a>
                    </li>
                    <li>
                        <a href="/Account/Register">Sign Up</a>
                    </li>
                    <li>
                        <a href="/Account/Login">Sign In</a>
                    </li>

                </ul>
            </li>
        </ul>
    </div>
</nav>

YSManagmentSystem.web/Views/Shared/_Sidebar.cshtml
<div class="nk-sidebar">
    <div class="nk-nav-scroll">
        <ul class="metismenu" id="menu">
             <li class="nav-label">
                 <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
             </li>
             <li class="nav-item">
                 <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users List</a>
             </li>
             <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Sign Up</a>
             </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Sign In</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="CreateOrder">Create Order</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products List</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories List</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Orders List</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customers List</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Brand" asp-action="Index">Brands List</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Supplier" asp-action="Index">Suppliers List</a>
            </li>

        </ul>
    </div>
</div>